# Generated by Django 5.2.5 on 2025-09-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_tags_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
