# Generated by Django 5.2.5 on 2025-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('drfat', 'Draft'), ('published', 'Published')], default='draft', max_length=100),
        ),
    ]
